name: learn-github-actions
on: [push, repository_dispatch]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "papascott@gmail.com"
          curl http://drummer.scripting.com/ScottHansonDE/papascott-de.opml -o papascott-de.opml
          git add papascott-de.opml
          git commit -m "Fetched papascott-de.opml"
          git push origin main
