name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: npm install bats
      - run: bats -v
      - shell: bash
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "papascott@gmail.com"
          git add package*
          git commit -m "Installed bats"
          git push origin main
